// <auto-generated />
using System;
using BookingSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251217102632_AddClassSchedules")]
    partial class AddClassSchedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookingSystem.Domain.Entities.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("RequiredCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("CountryId", "StartTime", "IsActive");

                    b.ToTable("ClassSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 1",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 2,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 18, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 1",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 3,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 19, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 2",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 4,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 19, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 19, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 2",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 5,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 3",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 6,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 20, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 3",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 7,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 4",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 8,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 21, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 4",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 9,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 5",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 10,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 22, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 22, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 5",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 11,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 23, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 6",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 12,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 23, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 23, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 6",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 13,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 24, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 7",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 14,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 24, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 24, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 7",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 15,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 8",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 16,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 25, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 25, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 8",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 17,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 26, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 26, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 9",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 18,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 26, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 26, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 9",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 19,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 27, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 10",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 20,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 27, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 27, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 10",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 21,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 28, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 11",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 22,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 28, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 28, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 11",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 23,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 29, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 29, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 12",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 24,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 29, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 29, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 12",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 25,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 30, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 13",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 26,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 30, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 30, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 13",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 27,
                            AvailableSlots = 15,
                            Capacity = 15,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Start your day with energizing yoga poses and breathing exercises. Suitable for all levels.",
                            EndTime = new DateTime(2025, 12, 31, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 31, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Morning Yoga - Day 14",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 28,
                            AvailableSlots = 20,
                            Capacity = 20,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352),
                            Description = "High-intensity interval training to boost your metabolism and build strength. Intermediate level.",
                            EndTime = new DateTime(2025, 12, 31, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RequiredCredits = 1,
                            RowVersion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 12, 31, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Evening HIIT - Day 14",
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(1352)
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SG",
                            IsActive = true,
                            Name = "Singapore",
                            TimeZone = "Asia/Singapore"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MY",
                            IsActive = true,
                            Name = "Malaysia",
                            TimeZone = "Asia/Kuala_Lumpur"
                        },
                        new
                        {
                            Id = 3,
                            Code = "TH",
                            IsActive = true,
                            Name = "Thailand",
                            TimeZone = "Asia/Bangkok"
                        },
                        new
                        {
                            Id = 4,
                            Code = "US",
                            IsActive = true,
                            Name = "United States",
                            TimeZone = "America/New_York"
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "IsActive");

                    b.ToTable("Packages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(8644),
                            Credits = 5,
                            IsActive = true,
                            Name = "Trial Pack",
                            Price = 50.00m,
                            ValidityDays = 30
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(8646),
                            Credits = 10,
                            IsActive = true,
                            Name = "Standard Pack",
                            Price = 90.00m,
                            ValidityDays = 60
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(8648),
                            Credits = 20,
                            IsActive = true,
                            Name = "Premium Pack",
                            Price = 160.00m,
                            ValidityDays = 90
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 26, 31, 6, DateTimeKind.Utc).AddTicks(8649),
                            Credits = 50,
                            IsActive = true,
                            Name = "Ultimate Pack",
                            Price = 350.00m,
                            ValidityDays = 180
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("User");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmailVerificationToken");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.UserPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsExpired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("RemainingCredits")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("ExpiresAt", "IsExpired");

                    b.HasIndex("UserId", "IsExpired", "ExpiresAt");

                    b.ToTable("UserPackages", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.ClassSchedule", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Country", "Country")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Package", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Country", "Country")
                        .WithMany("Packages")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.UserPackage", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Package", "Package")
                        .WithMany("UserPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingSystem.Domain.Entities.User", "User")
                        .WithMany("UserPackages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Country", b =>
                {
                    b.Navigation("ClassSchedules");

                    b.Navigation("Packages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Package", b =>
                {
                    b.Navigation("UserPackages");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("UserPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
